FROM golang:1.6

ENV GOBIN=/usr/local/bin

COPY . /go/src/app
COPY ./docker/PagerDutyServiceKey /etc/PagerDutyServiceKey
RUN mkdir -p /go/src/github.com/gudtech/scamp-go && \
    ln -s /go/src/app/scamp /go/src/github.com/gudtech/scamp-go/scamp && \
    go get golang.org/x/net/ipv4 && \
    go install /go/src/app/bin/watchdog2.go